### ISSUE TITLE
How Cregis optimization in optimization

### ISSUE THREAD

**Issue by Gesge** [0xcregis/anychain#161]

**Comment by cosminmart** [comment]
```toml
[profile.release]
strip = true       # Automatically strip symbols from the binary
opt-level = "s"    # Optimize for size
lto = true         # Enable link time optimization
codegen-units = 1  # Maximize size reduction optimizations
```

The settings indicate that debugging information should be included (debug = true), link-time optimization should be enabled (lto = true), and the project should be built with a single code generation unit (codegen-units = 1). These settings can help improve the performance and efficiency of the final release build of the project.

**Comment by shuimuliang** [comment]
```toml
[profile.release]
strip = true       # Automatically strip symbols from the binary
opt-level = "s"    # Optimize for size
lto = true         # Enable link time optimization
codegen-units = 1  # Maximize size reduction optimizations
```

The settings indicate that debugging information should be included (debug = true), link-time optimization should be enabled (lto = true), and the project should be built with a single code generation unit (codegen-units = 1). These settings can help improve the performance and efficiency of the final release build of the project.
